server:
  port: 8002
spring:
  application:
    name: crm-systemset
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?useunicode=true;&characterEncoding=utf8&serverTimezone=UTC
    password: root
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
swagger:
  base-package: com.crm.web.controller